# Generated by Django 4.2.5 on 2023-11-23 16:55

from django.db import migrations, models
import django.db.models.deletion

def create_default_type_dachat(apps, schema_editor):
    typedachat = apps.get_model('achats', 'TypeDachat')
    typedachat.objects.create(type='Contrat Cadre')
    typedachat.objects.create(type='Achat Direct')
    typedachat.objects.create(type="Appel d'offre")
    typedachat.objects.create(type="Achat en ligne")
    typedachat.objects.create(type="Convention Partenari")


def create_default_situation_dachat(apps, schema_editor):
    situation_dachat = apps.get_model('achats', 'SituationDachat')
    situation_dachat.objects.create(situation='Pré DA')
    situation_dachat.objects.create(situation='DA en cours')
    situation_dachat.objects.create(situation="Non Livré")
    situation_dachat.objects.create(situation="Livré")
    situation_dachat.objects.create(situation="Livraison partielle")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantité', models.IntegerField()),
                ('valable', models.IntegerField(default=0)),
                ('reste', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SituationDachat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDachat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Contrat Cadre', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDArticle',
            fields=[
                ('type', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('prix_estimatif', models.IntegerField(blank=True, null=True)),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='achats.contrat')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='achats.typedarticle')),
            ],
        ),
        migrations.CreateModel(
            name='Achats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demandeur', models.CharField(max_length=100)),
                ('entité', models.CharField(max_length=100)),
                ('ligne_bugetaire', models.CharField(max_length=30)),
                ('DateDeCommande', models.DateField()),
                ('DA', models.CharField(blank=True, max_length=30, null=True)),
                ('DateDA', models.DateField(blank=True, null=True)),
                ('BC', models.CharField(blank=True, max_length=30, null=True)),
                ('DateBC', models.DateField(blank=True, null=True)),
                ('BC_File', models.FileField(blank=True, null=True, upload_to='uploads/BC')),
                ('BL', models.CharField(blank=True, max_length=30, null=True)),
                ('DateBL', models.DateField(blank=True, null=True)),
                ('BL_File', models.FileField(blank=True, null=True, upload_to='uploads/BL')),
                ('observation', models.TextField(blank=True, null=True)),
                ('isComplet', models.BooleanField(default=False)),
                ('consommable', models.BooleanField(default=False)),
                ('apple', models.BooleanField(default=False)),
                ('fourniseur', models.CharField(blank=True, max_length=60, null=True)),
                ('TV', models.IntegerField(blank=True, null=True)),
                ('TT', models.IntegerField(blank=True, null=True)),
                ('TL', models.IntegerField(blank=True, null=True)),
                ('achat', models.ManyToManyField(to='achats.achat')),
                ('situation_d_achat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='achats.situationdachat')),
                ('typeDachat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='achats.typedachat')),
            ],
        ),
        migrations.AddField(
            model_name='achat',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='achats.article'),
        ),
        migrations.RunPython(create_default_type_dachat),
        migrations.RunPython(create_default_situation_dachat),
    ]
