# Generated by Django 4.2.5 on 2023-10-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='fourniseur',
        ),
        migrations.AddField(
            model_name='achats',
            name='fourniseur',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
