# Generated by Django 4.2.5 on 2023-10-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_alter_article_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='isComplet',
            field=models.BooleanField(default=False),
        ),
    ]
