# Generated by Django 4.2.5 on 2023-10-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0004_remove_achats_tl_remove_achats_tt_remove_achats_tv'),
    ]

    operations = [
        migrations.AddField(
            model_name='achats',
            name='TL',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achats',
            name='TT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achats',
            name='TV',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
