# Generated by Django 4.2.5 on 2023-10-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0006_achats_apple_achats_consommable'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='valable',
            field=models.IntegerField(default=0),
        ),
    ]
