# Generated by Django 4.2.5 on 2023-11-03 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomPrenom', models.CharField(blank=True, max_length=100, null=True)),
                ('Fonction', models.CharField(blank=True, max_length=50, null=True)),
                ('situation', models.CharField(blank=True, max_length=100, null=True)),
                ('DateArrivage', models.DateField(blank=True, null=True)),
                ('serviceTag', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockEtat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(default='Stock', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField()),
                ('quantité', models.IntegerField(default=0)),
                ('stocks', models.ManyToManyField(to='Stock.stock')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achats.typedarticle')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='etat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.stocketat'),
        ),
        migrations.CreateModel(
            name='inStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BC', models.CharField(max_length=30)),
                ('fourniseur', models.CharField(blank=True, max_length=30, null=True)),
                ('entité', models.CharField(max_length=50)),
                ('stocks', models.ManyToManyField(to='Stock.stocks')),
            ],
        ),
    ]
