# Generated by Django 4.2.5 on 2023-11-01 16:02

from django.db import migrations, models
import django.db.models.deletion


def create_default_etat(apps, schema_editor):
    etat = apps.get_model('Stock', 'StockEtat')
    etat.objects.create(etat='Stock')
    etat.objects.create(etat='Affecté')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achats', '0009_remove_stock_etat_remove_stock_type_delete_instock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEtat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(default='Stock', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomPrenom', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.TextField()),
                ('Fonction', models.CharField(blank=True, max_length=50, null=True)),
                ('situation', models.CharField(blank=True, max_length=100, null=True)),
                ('DateArrivage', models.DateField()),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.stocketat')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achats.typedarticle')),
            ],
        ),
        migrations.CreateModel(
            name='inStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BC', models.CharField(max_length=30)),
                ('fourniseur', models.CharField(max_length=30)),
                ('entité', models.CharField(max_length=50)),
                ('stock', models.ManyToManyField(to='Stock.stock')),
            ],
        ),
        migrations.RunPython(create_default_etat),
    ]
