# Generated by Django 4.2.5 on 2023-11-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='DateDaffectation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
