# Generated by Django 4.2.5 on 2023-11-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='affecté',
            field=models.IntegerField(default=0),
        ),
    ]
