# Generated by Django 4.2.5 on 2023-11-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_stock_datedaffectation_stock_affected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='stocks',
            field=models.ManyToManyField(related_name='related_stocks', to='Stock.stock'),
        ),
    ]
