# Generated by Django 4.2.5 on 2023-09-25 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def create_default_type_products(apps, schema_editor):
    TypeProduct = apps.get_model('products', 'TypeProduct')
    TypeProduct.objects.create(name="laptop")
    TypeProduct.objects.create(name="desktop")
    TypeProduct.objects.create(name="phone")

def create_default_etat_products(apps, schema_editor):
    EtatProduct = apps.get_model('products', 'EtatProduct')
    EtatProduct.objects.create(name='arrivé')
    EtatProduct.objects.create(name='attente')
    EtatProduct.objects.create(name='affecté')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatProduct',
            fields=[
                ('name', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('new_etat', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('name', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('date_d_arivage', models.DateField()),
                ('nom_prenom', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('entite', models.CharField(max_length=100)),
                ('name_product', models.CharField(max_length=100)),
                ('service_tag', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('date_d_integration', models.DateField(blank=True, null=True)),
                ('date_d_affectation', models.DateField(blank=True, null=True)),
                ('iccid', models.CharField(blank=True, max_length=23, null=True)),
                ('nd', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('audit_logs', models.ManyToManyField(blank=True, related_name='products_audit_logs', to='products.productauditlog')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('etat_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.etatproduct')),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.typeproduct')),
            ],
        ),
        migrations.AddField(
            model_name='productauditlog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.AddField(
            model_name='productauditlog',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
        migrations.RunPython(create_default_type_products),
        migrations.RunPython(create_default_etat_products),
    ]
