# Generated by Django 4.2.5 on 2023-11-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_is_achat_manager_customuser_is_reception'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_achat_manager',
            field=models.BooleanField(default=False),
        ),
    ]
