# Generated by Django 4.2.5 on 2023-11-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_achat_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agent_affectation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
