# Generated by Django 4.2.5 on 2023-11-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_agent_affectation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='proffession',
        ),
    ]
